// DATA
const CATEGORIES = {
  "Países": ["Argentina", "Brasil", "Chile", "Uruguay", "Paraguay", "Bolivia", "Perú", "Ecuador", "Colombia", "Venezuela", "México", "Estados Unidos", "Canadá", "España", "Portugal", "Francia", "Italia", "Alemania", "Reino Unido", "Irlanda", "Escocia", "Países Bajos", "Bélgica", "Suiza", "Austria", "Suecia", "Noruega", "Finlandia", "Dinamarca", "Islandia", "Polonia", "República Checa", "Hungría", "Rumania", "Grecia", "Turquía", "Rusia", "Ucrania", "China", "Japón", "Corea del Sur", "India", "Pakistan", "Nepal", "Tailandia", "Vietnam", "Indonesia", "Filipinas", "Australia", "Nueva Zelanda", "Egipto", "Marruecos", "Argelia", "Túnez", "Sudáfrica", "Nigeria", "Kenia", "Etiopía", "Ghana", "Senegal", "Camerún", "Arabia Saudita", "Emiratos Árabes", "Israel", "Irán", "Irak", "Qatar", "Kuwait", "Jordania", "Líbano", "Singapur", "Malasia", "Bangladesh", "Sri Lanka", "Myanmar", "Camboya", "Laos", "Mongolia", "Kazajistán", "Uzbekistán", "Afganistán", "Luxemburgo", "Liechtenstein", "San Marino", "Mónaco", "Andorra", "Malta", "Costa Rica", "Panamá", "Cuba", "Guatemala", "Honduras", "El Salvador", "Nicaragua", "Islandia", "Croacia", "Serbia", "Francia", "Uzbekistán", "Chile", "Dinamarca", "Malasia", "Túnez", "Islandia", "Túnez", "Túnez", "Jordania", "Uzbekistán", "Australia", "Austria", "Chile", "Suiza", "El Salvador", "Estados Unidos", "Indonesia", "Ghana", "Singapur", "República Checa", "Mónaco", "Filipinas", "Luxemburgo", "Escocia", "Suiza", "El Salvador", "Suiza", "Arabia Saudita", "Chile", "Perú", "República Checa", "Kazajistán", "Egipto", "Hungría", "México", "Islandia", "Jordania", "Filipinas", "El Salvador", "República Checa", "Austria", "República Checa", "Singapur", "Chile", "Austria", "India", "Austria", "Austria", "Singapur", "Andorra", "Filipinas", "Francia"],
  "Fútbol": ["Lionel Messi", "Cristiano Ronaldo", "Diego Maradona", "Pelé", "Johan Cruyff", "Zinedine Zidane", "Ronaldinho", "Ronaldo Nazario", "Neymar", "Kylian Mbappé", "Erling Haaland", "Kevin De Bruyne", "Luka Modrić", "Xavi", "Andrés Iniesta", "Sergio Busquets", "Thierry Henry", "Robert Lewandowski", "Karim Benzema", "Mohamed Salah", "Sadio Mané", "Harry Kane", "Wayne Rooney", "Paul Scholes", "David Beckham", "Steven Gerrard", "Frank Lampard", "Raúl", "Iker Casillas", "Gianluigi Buffon", "Manuel Neuer", "Thibaut Courtois", "Marc-André ter Stegen", "Virgil van Dijk", "Sergio Ramos", "Gerard Piqué", "Carles Puyol", "Franco Baresi", "Paolo Maldini", "Alessandro Del Piero", "Francesco Totti", "Andrea Pirlo", "Clarence Seedorf", "Kaká", "Rivaldo", "Romário", "Gabriel Batistuta", "Juan Román Riquelme", "Carlos Tevez", "Ángel Di María", "Lautaro Martínez", "Julián Álvarez", "Paulo Dybala", "Edinson Cavani", "Luis Suárez", "Diego Forlán", "Alexis Sánchez", "Arturo Vidal", "James Rodríguez", "Radamel Falcao", "Iván Zamorano", "Hugo Sánchez", "Cuauhtémoc Blanco", "Mario Alberto Kempes", "Daniel Passarella", "Osvaldo Ardiles", "Ubaldo Fillol", "Jorge Valdano", "Claudio Caniggia", "Hernán Crespo", "Javier Zanetti", "Pablo Aimar", "Roberto Ayala", "Walter Samuel", "Carlos Bilardo", "Juan Sebastián Verón", "Esteban Cambiasso", "Diego Milito", "Gonzalo Higuaín", "Ezequiel Lavezzi", "Ever Banega", "Lucas Leiva", "Emiliano Martínez", "Cristian Romero", "Nicolás Otamendi", "Marcos Acuña", "Leandro Paredes", "Rodrigo De Paul", "Enzo Fernández", "Alexis Mac Allister", "Nicolás Tagliafico", "Ángel Correa", "Alejandro Garnacho", "Thiago Almada", "Giovani Lo Celso", "Pep Guardiola", "Jürgen Klopp", "Carlo Ancelotti", "José Mourinho", "Marcelo Bielsa", "Diego Simeone", "Alex Ferguson", "Arsène Wenger", "Louis van Gaal", "Vicente del Bosque", "Ottmar Hitzfeld", "Fabio Capello", "Arrigo Sacchi", "Roberto Mancini", "Massimiliano Allegri", "Antonio Conte", "Unai Emery", "Julian Nagelsmann", "Didier Deschamps", "Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla", "Valencia", "Real Sociedad", "Villarreal", "Manchester United", "Manchester City", "Liverpool", "Chelsea", "Arsenal", "Tottenham", "Newcastle United", "Bayern Munich", "Borussia Dortmund", "RB Leipzig", "Bayer Leverkusen", "PSG", "Olympique de Marsella", "Olympique Lyon", "Monaco", "Juventus", "Milan", "Inter de Milan", "Napoli", "Roma", "Lazio", "Atalanta", "Ajax", "PSV Eindhoven", "Feyenoord", "Benfica", "Porto", "Sporting Lisboa", "Talleres", "Belgrano", "Boca jr", "River Plate", "Newell's", "Rosario Central", "Racing", "Independiente", "Estudiantes de la Plata", "Inter de Miami"],
  "Cine y TV": ["El secreto de sus ojos", "Nueve reinas", "Relatos salvajes", "Esperando la carroza", "La historia oficial", "Argentina 1985", "El hijo de la novia", "La Odisea de los Giles", "Un novio para mi mujer", "Luna de Avellaneda", "Carancho", "Pizza birra faso", "El clan", "El aura", "Medianeras", "La odisea de los giles", "Mi obra maestra", "El robo del siglo", "Corazon de Leon", "Los simuladores", "Casados con hijos", "El marginal", "Okupas", "Tumberos", "Vientos de agua", "Hermanos y detectives", "Graduados", "El puntero", "ATAV", "Resistiré", "Casi ángeles", "Chiquititas", "Floricienta", "Las Estrellas", "Showmatch", "Videomatch", "Polémica en el bar", "Intratables", "Periodismo para todos", "PH Podemos Hablar", "Almorzando con Mirtha Legrand", "CQC", "Bendita TV", "LAM", "MasterChef", "Gran Hermano", "Pasapalabra", "El precio justo", "Perros de la calle", "Basta de todo", "Peligro sin codificar", "El Padrino", "El Padrino II", "Rocky", "Rambo", "Forrest Gump", "Titanic", "Avatar", "Inception", "Interestelar", "Gladiador", "Jurassic Park", "Volver al futuro", "Terminator", "Matrix", "Pulp Fiction", "El club de la pelea", "Batman", "Avengers", "Iron Man", "Spider-Man", "Star Wars", "Indiana Jones", "Harry Potter", "El señor de los anillos", "Tiburon", "Rocky Balboa", "Top Gun", "Taxi Driver", "Scarface", "It", "Breaking Bad", "Better Call Saul", "Game of Thrones", "The Walking Dead", "Friends", "The Office", "Greys Anatomy", "Lost", "Dr House", "Prison Break", "Dexter", "Stranger Things", "Dark", "Peaky Blinders", "Vikings", "The Big Bang Theory", "Seinfeld", "Black Mirror", "The Boys", "La casa de Papel", "Coscu", "Momo", "Spreen", "Tomas Rebord", "Ruffo (Blender)", "Ibai", "Luisito Comunica", "Luquitas Rodríguez", "La Cobra", "Davoo Xeneize", "RodSquare", "Ricky Fort", "Martin Cirio", "Les Amateurs", "Olga", "Luzu TV", "Vorterix", "Blender", "Gelatina", "Paren la mano (Vorterix)", "Hay algo ahi (Blender)", "Nadie dice nada (Luzu)", "Soñé que volaba (Olga)", "Antes que nadie (Luzu)", "Oppenheimer", "Barbie", "The Crown", "House of Cards", "Narcos", "The Mandalorian", "The Simpsons", "South Park", "Rick and Morty", "Wednesday", "Peligro sin codificar", "La odisea de los giles", "Medianeras", "Dexter", "Rocky Balboa", "Casi ángeles", "Los simuladores", "Olga", "Scarface", "El clan", "The Walking Dead", "Matrix", "Videomatch", "Casados con hijos", "Star Wars"],
  "Famosos Arg": ["Lionel Messi", "Diego Maradona", "Ángel Di María", "Paulo Dybala", "Sergio Agüero", "Carlos Tevez", "Juan Román Riquelme", "Gabriel Batistuta", "Javier Zanetti", "Franco Colapinto", "Emanuel Ginóbili", "Luis Scola", "Juan Martín del Potro", "Guillermo Vilas", "Marcos Maidana", "Sergio Martínez", "Luciana Aymar", "Paula Pareto", "Martin Palermo", "Oscar Ruggeri", "Marcelo Tinelli", "Susana Giménez", "Mirtha Legrand", "Guillermo Francella", "Ricardo Darín", "Adrián Suar", "Florencia Peña", "Luciano Castro", "Marley", "Santiago del Moro", "Ángel de Brito", "Jorge Rial", "Viviana Canosa", "Pampita", "Yanina Latorre", "Wanda Nara", "Marcelo Polino", "Guido Kaczka", "Darío Barassi", "Charly García", "Gustavo Cerati", "Fito Páez", "Spinetta", "Indio Solari", "Andrés Calamaro", "Lali Espósito", "Tini Stoessel", "Nicki Nicole", "Duki", "Trueno", "Maria Becerra", "Bizarrap", "La Mona Jimenez", "Rodrigo Bueno", "Q Lokura", "Coscu", "Momo", "Spreen", "Luquitas Rodríguez", "La Cobra", "Davoo Xeneize", "Martin Cirio", "Joaco López", "Mernuel", "Ricardo Fort", "Vicky Xipolitakis", "Alex Caniggia", "Charlotte Caniggia", "Milei", "Peron", "Nestor Kirchner", "Cristina Kirchner", "Eva Peron", "Mauricio Macri", "Juan Domingo Perón", "Eva Perón", "Cristina Fernández", "Javier Milei", "Mauricio Macri", "Raúl Alfonsín", "Carlos Menem", "Domingo Sarmiento", "José de San Martín", "Manuel Belgrano", "Diego Maradona", "Paula Pareto", "Cristina Kirchner", "Vicky Xipolitakis", "La Mona Jimenez", "Guido Kaczka", "Susana Giménez", "Eva Perón", "Mauricio Macri", "Mernuel", "Paulo Dybala", "Cristina Kirchner", "Marcos Maidana", "Ricardo Fort", "Guido Kaczka", "Eva Peron", "Marcos Maidana", "La Mona Jimenez", "Ricardo Darín", "Alex Caniggia", "Adrián Suar", "Eva Peron", "Ricardo Fort", "Vicky Xipolitakis", "Pampita", "Manuel Belgrano", "Franco Colapinto", "Mirtha Legrand", "Ricardo Darín", "Darío Barassi", "Gustavo Cerati", "Gustavo Cerati", "Martin Cirio", "Duki", "Gustavo Cerati", "Martin Cirio", "Javier Milei", "Mirtha Legrand", "Juan Román Riquelme", "Gabriel Batistuta", "Andrés Calamaro", "Pampita", "Bizarrap", "Vicky Xipolitakis", "Ángel Di María", "Diego Maradona", "Diego Maradona", "Jorge Rial", "Mirtha Legrand", "Marcelo Tinelli", "Luciana Aymar", "Susana Giménez", "Rodrigo Bueno", "Eva Peron", "Ricardo Darín", "Marcos Maidana", "Eva Peron", "Marley", "Joaco López", "Cristina Kirchner", "Viviana Canosa", "Sergio Agüero", "Jorge Rial", "Diego Maradona", "Guido Kaczka", "Darío Barassi"],
  "Famosos": ["Leonardo DiCaprio", "Brad Pitt", "Tom Cruise", "Johnny Depp", "Robert Downey Jr", "Al Pacino", "Robert De Niro", "Denzel Washington", "Will Smith", "Keanu Reeves", "Matt Damon", "Christian Bale", "Ryan Gosling", "Hugh Jackman", "Jason Statham", "Scarlett Johansson", "Margot Robbie", "Angelina Jolie", "Jennifer Lawrence", "Emma Stone", "Michael Jackson", "Madonna", "Elvis Presley", "Queen", "Freddie Mercury", "The Beatles", "Paul McCartney", "John Lennon", "Beyoncé", "Rihanna", "Taylor Swift", "Lady Gaga", "Bruno Mars", "Drake", "Eminem", "Kanye West", "Justin Bieber", "Shakira", "Bad Bunny", "The Weeknd", "Daddy Yankee", "Cristiano Ronaldo", "Neymar", "Kylian Mbappé", "Zinedine Zidane", "Ronaldinho", "Pelé", "Michael Jordan", "LeBron James", "Kobe Bryant", "Stephen Curry", "Roger Federer", "Rafael Nadal", "Novak Djokovic", "Usain Bolt", "Mike Tyson", "Elon Musk", "Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos", "Barack Obama", "Donald Trump", "Einstein", "Stephen Hawking", "Bruce Lee", "Oprah Winfrey", "Kim Kardashian", "Selena Gomez", "Cristiano Ronaldo", "Lionel Messi", "David Beckham", "Jackie Chan", "Tom Hanks", "Morgan Freeman", "Jack Nicholson", "David Beckham", "Shakira", "Jackie Chan", "Barack Obama", "Tom Cruise", "Selena Gomez", "Ryan Gosling", "Denzel Washington", "Cristiano Ronaldo", "Cristiano Ronaldo", "Emma Stone", "Emma Stone", "Roger Federer", "Kanye West", "Drake", "Leonardo DiCaprio", "Michael Jackson", "Kanye West", "Kanye West", "Keanu Reeves", "Margot Robbie", "Tom Cruise", "Taylor Swift", "Neymar", "Rafael Nadal", "Kanye West", "Rihanna", "Brad Pitt", "Madonna", "Christian Bale", "Michael Jordan", "Rafael Nadal", "Emma Stone", "Mark Zuckerberg", "Stephen Hawking", "Ryan Gosling", "Neymar", "Will Smith", "Jack Nicholson", "David Beckham", "Denzel Washington", "Paul McCartney", "Ryan Gosling", "Pelé", "David Beckham", "Pelé", "Rihanna", "Michael Jackson", "Usain Bolt", "Steve Jobs", "Bruce Lee", "Steve Jobs", "Morgan Freeman", "Usain Bolt", "Will Smith", "Stephen Hawking", "Matt Damon", "Kobe Bryant", "Margot Robbie", "Emma Stone", "Keanu Reeves", "Jason Statham", "Kanye West", "Mark Zuckerberg", "David Beckham", "Neymar", "Denzel Washington", "Steve Jobs", "Kanye West", "Keanu Reeves", "Barack Obama", "Ryan Gosling", "Lady Gaga", "Margot Robbie"],
  "Objetos": ["Silla", "Mesa", "Sillón", "Cama", "Almohada", "Colchón", "Lámpara", "Ventilador", "Aire acondicionado", "Televisor", "Control remoto", "Cortina", "Espejo", "Reloj de pared", "Cuadro", "Plato", "Vaso", "Taza", "Cuchara", "Tenedor", "Cuchillo", "Sartén", "Olla", "Horno", "Microondas", "Heladera", "Licuadora", "Pava eléctrica", "Cafetera", "Tostadora", "Celular", "Computadora", "Notebook", "Tablet", "Mouse", "Teclado", "Monitor", "Impresora", "Router", "Modem", "Auriculares", "Parlante", "Cargador", "Batería", "Disco rígido", "Cuaderno", "Libro", "Agenda", "Lapicera", "Lápiz", "Resaltador", "Borrador", "Regla", "Carpeta", "Mochila", "Martillo", "Destornillador", "Alicate", "Taladro", "Llave inglesa", "Clavo", "Tornillo", "Cinta métrica", "Tijera", "Cinta adhesiva", "Reloj pulsera", "Anillo", "Collar", "Anteojos", "Gorra", "Zapatillas", "Campera", "Billetera", "Llaves", "Paraguas", "Drone", "Smartwatch", "Joystick", "Consola", "Proyector", "Escáner", "Termómetro", "Linterna", "Trípode", "Cámara", "Lápiz", "Consola", "Cinta métrica", "Cargador", "Llaves", "Drone", "Modem", "Cargador", "Batería", "Zapatillas", "Cortina", "Cuadro", "Mouse", "Teclado", "Joystick", "Horno", "Disco rígido", "Espejo", "Tijera", "Mouse", "Resaltador", "Computadora", "Espejo", "Tablet", "Espejo", "Heladera", "Batería", "Libro", "Llaves", "Disco rígido", "Microondas", "Computadora", "Aire acondicionado", "Resaltador", "Sillón", "Espejo", "Reloj pulsera", "Martillo", "Borrador", "Proyector", "Tijera", "Celular", "Computadora", "Regla", "Cinta métrica", "Collar", "Espejo", "Borrador", "Mouse", "Cama", "Televisor", "Monitor", "Lápiz", "Microondas", "Mouse", "Lápiz", "Cuaderno", "Anteojos", "Computadora", "Alicate", "Cuadro", "Cuadro", "Cinta adhesiva", "Campera", "Cortina"],
};

const PISTAS = {
  "Argentina":"País de América del Sur",
"Brasil":"País de América del Sur",
"Chile":"País de América del Sur",
"Uruguay":"País de América del Sur",
"Paraguay":"País de América del Sur",
"Bolivia":"País de América del Sur",
"Perú":"País de América del Sur",
"Ecuador":"País de América del Sur",
"Colombia":"País de América del Sur",
"Venezuela":"País de América del Sur",

"México":"País de América del Norte",
"Estados Unidos":"País de América del Norte",
"Canadá":"País de América del Norte",

"España":"País europeo",
"Portugal":"País europeo",
"Francia":"País europeo",
"Italia":"País europeo",
"Alemania":"País europeo",
"Reino Unido":"País europeo",
"Irlanda":"País europeo",
"Escocia":"País europeo",
"Países Bajos":"País europeo",
"Bélgica":"País europeo",
"Suiza":"País europeo",
"Austria":"País europeo",
"Suecia":"País europeo",
"Noruega":"País europeo",
"Finlandia":"País europeo",
"Dinamarca":"País europeo",
"Islandia":"País europeo",
"Polonia":"País europeo",
"República Checa":"País europeo",
"Hungría":"País europeo",
"Rumania":"País europeo",
"Grecia":"País europeo",
"Croacia":"País europeo",
"Serbia":"País europeo",
"Luxemburgo":"País europeo",
"Liechtenstein":"País europeo",
"San Marino":"País europeo",
"Mónaco":"País europeo",
"Andorra":"País europeo",
"Malta":"País europeo",
"Ucrania":"País europeo",

"Turquía":"País euroasiático",
"Rusia":"País euroasiático",

"China":"País asiático",
"Japón":"País asiático",
"Corea del Sur":"País asiático",
"India":"País asiático",
"Pakistan":"País asiático",
"Nepal":"País asiático",
"Tailandia":"País asiático",
"Vietnam":"País asiático",
"Indonesia":"País asiático",
"Filipinas":"País asiático",
"Singapur":"País asiático",
"Malasia":"País asiático",
"Bangladesh":"País asiático",
"Sri Lanka":"País asiático",
"Myanmar":"País asiático",
"Camboya":"País asiático",
"Laos":"País asiático",
"Mongolia":"País asiático",
"Kazajistán":"País asiático",
"Uzbekistán":"País asiático",
"Afganistán":"País asiático",
"Israel":"País de Medio Oriente",
"Irán":"País de Medio Oriente",
"Irak":"País de Medio Oriente",
"Qatar":"País de Medio Oriente",
"Kuwait":"País de Medio Oriente",
"Jordania":"País de Medio Oriente",
"Líbano":"País de Medio Oriente",
"Arabia Saudita":"País de Medio Oriente",
"Emiratos Árabes":"País de Medio Oriente",

"Egipto":"País africano",
"Marruecos":"País africano",
"Argelia":"País africano",
"Túnez":"País africano",
"Sudáfrica":"País africano",
"Nigeria":"País africano",
"Kenia":"País africano",
"Etiopía":"País africano",
"Ghana":"País africano",
"Senegal":"País africano",
"Camerún":"País africano",

"Australia":"País de Oceanía",
"Nueva Zelanda":"País de Oceanía",

"Costa Rica":"País de América Central",
"Panamá":"País de América Central",
"Cuba":"País del Caribe",
"Guatemala":"País de América Central",
"Honduras":"País de América Central",
"El Salvador":"País de América Central",
"Nicaragua":"País de América Central",
  "Lionel Messi":"Jugador de élite",
"Cristiano Ronaldo":"Jugador de élite",
"Diego Maradona":"Leyenda del fútbol",
"Pelé":"Leyenda del fútbol",
"Johan Cruyff":"Jugador histórico",
"Zinedine Zidane":"Jugador histórico",
"Ronaldinho":"Jugador histórico",
"Ronaldo Nazario":"Delantero histórico",
"Neymar":"Jugador brasileño",
"Kylian Mbappé":"Delantero europeo",
"Erling Haaland":"Delantero europeo",
"Kevin De Bruyne":"Mediocampista europeo",
"Luka Modrić":"Mediocampista europeo",
"Xavi":"Mediocampista histórico",
"Andrés Iniesta":"Mediocampista histórico",
"Sergio Busquets":"Mediocampista español",
"Thierry Henry":"Delantero histórico",
"Robert Lewandowski":"Delantero europeo",
"Karim Benzema":"Delantero europeo",
"Mohamed Salah":"Delantero africano",
"Sadio Mané":"Delantero africano",
"Harry Kane":"Delantero inglés",
"Wayne Rooney":"Delantero histórico",
"Paul Scholes":"Mediocampista inglés",
"David Beckham":"Jugador inglés",
"Steven Gerrard":"Mediocampista inglés",
"Frank Lampard":"Mediocampista inglés",
"Raúl":"Delantero español",
"Iker Casillas":"Arquero histórico",
"Gianluigi Buffon":"Arquero histórico",
"Manuel Neuer":"Arquero alemán",
"Thibaut Courtois":"Arquero europeo",
"Marc-André ter Stegen":"Arquero alemán",
"Virgil van Dijk":"Defensor europeo",
"Sergio Ramos":"Defensor histórico",
"Gerard Piqué":"Defensor español",
"Carles Puyol":"Defensor histórico",
"Franco Baresi":"Defensor histórico",
"Paolo Maldini":"Defensor histórico",
"Alessandro Del Piero":"Delantero italiano",
"Francesco Totti":"Jugador italiano",
"Andrea Pirlo":"Mediocampista histórico",
"Clarence Seedorf":"Mediocampista histórico",
"Kaká":"Mediocampista brasileño",
"Rivaldo":"Jugador brasileño",
"Romário":"Delantero brasileño",

"Gabriel Batistuta":"Delantero argentino",
"Juan Román Riquelme":"Jugador argentino",
"Carlos Tevez":"Delantero argentino",
"Ángel Di María":"Jugador argentino",
"Lautaro Martínez":"Delantero argentino",
"Julián Álvarez":"Delantero argentino",
"Paulo Dybala":"Jugador argentino",

"Edinson Cavani":"Delantero uruguayo",
"Luis Suárez":"Delantero uruguayo",
"Diego Forlán":"Delantero uruguayo",
"Alexis Sánchez":"Jugador chileno",
"Arturo Vidal":"Jugador chileno",
"James Rodríguez":"Jugador colombiano",
"Radamel Falcao":"Delantero colombiano",
"Iván Zamorano":"Delantero chileno",
"Hugo Sánchez":"Delantero mexicano",
"Cuauhtémoc Blanco":"Jugador mexicano",

"Mario Alberto Kempes":"Delantero argentino",
"Daniel Passarella":"Defensor argentino",
"Osvaldo Ardiles":"Jugador argentino",
"Ubaldo Fillol":"Arquero argentino",
"Jorge Valdano":"Delantero argentino",
"Claudio Caniggia":"Delantero argentino",
"Hernán Crespo":"Delantero argentino",
"Javier Zanetti":"Defensor argentino",
"Pablo Aimar":"Mediocampista argentino",
"Roberto Ayala":"Defensor argentino",
"Walter Samuel":"Defensor argentino",
"Carlos Bilardo":"Entrenador argentino",
"Juan Sebastián Verón":"Mediocampista argentino",
"Esteban Cambiasso":"Mediocampista argentino",
"Diego Milito":"Delantero argentino",
"Gonzalo Higuaín":"Delantero argentino",
"Ezequiel Lavezzi":"Delantero argentino",
"Ever Banega":"Mediocampista argentino",
"Lucas Leiva":"Mediocampista brasileño",

"Emiliano Martínez":"Arquero argentino",
"Cristian Romero":"Defensor argentino",
"Nicolás Otamendi":"Defensor argentino",
"Marcos Acuña":"Jugador argentino",
"Leandro Paredes":"Mediocampista argentino",
"Rodrigo De Paul":"Mediocampista argentino",
"Enzo Fernández":"Mediocampista argentino",
"Alexis Mac Allister":"Mediocampista argentino",
"Nicolás Tagliafico":"Defensor argentino",
"Ángel Correa":"Delantero argentino",
"Alejandro Garnacho":"Delantero argentino",
"Thiago Almada":"Jugador argentino",
"Giovani Lo Celso":"Mediocampista argentino",

"Pep Guardiola":"Entrenador famoso",
"Jürgen Klopp":"Entrenador famoso",
"Carlo Ancelotti":"Entrenador famoso",
"José Mourinho":"Entrenador famoso",
"Marcelo Bielsa":"Entrenador argentino",
"Diego Simeone":"Entrenador argentino",
"Alex Ferguson":"Entrenador histórico",
"Arsène Wenger":"Entrenador histórico",
"Louis van Gaal":"Entrenador famoso",
"Vicente del Bosque":"Entrenador español",
"Ottmar Hitzfeld":"Entrenador europeo",
"Fabio Capello":"Entrenador italiano",
"Arrigo Sacchi":"Entrenador histórico",
"Roberto Mancini":"Entrenador italiano",
"Massimiliano Allegri":"Entrenador italiano",
"Antonio Conte":"Entrenador italiano",
"Unai Emery":"Entrenador español",
"Julian Nagelsmann":"Entrenador alemán",
"Didier Deschamps":"Entrenador francés",
  "Real Madrid":"Club de fútbol español",
  "Barcelona":"Club de fútbol español",
  "Atlético Madrid":"Club de fútbol español",
  "Sevilla":"Club de fútbol español",
  "Valencia":"Club de fútbol español",
  "Real Sociedad":"Club de fútbol español",
  "Villarreal":"Club de fútbol español",
  "Manchester United":"Club de fútbol inglés",
  "Manchester City":"Club de fútbol inglés",
  "Liverpool":"Club de fútbol inglés",
  "Chelsea":"Club de fútbol inglés",
  "Arsenal":"Club de fútbol inglés",
  "Tottenham":"Club de fútbol inglés",
  "Newcastle United":"Club de fútbol inglés",
  "Bayern Munich":"Club de fútbol alemán",
  "Borussia Dortmund":"Club de fútbol alemán",
  "RB Leipzig":"Club de fútbol alemán",
  "Bayer Leverkusen":"Club de fútbol alemán",
  "PSG":"Club de fútbol francés",
  "Olympique de Marsella":"Club de fútbol francés",
  "Olympique Lyon":"Club de fútbol francés",
  "Monaco":"Club de fútbol francés",
  "Juventus":"Club de fútbol italiano",
  "Milan":"Club de fútbol italiano",
  "Inter de Milan":"Club de fútbol italiano",
  "Napoli":"Club de fútbol italiano",
  "Roma":"Club de fútbol italiano",
  "Lazio":"Club de fútbol italiano",
  "Atalanta":"Club de fútbol italiano",
  "Ajax":"Club de fútbol neerlandés",
  "PSV Eindhoven":"Club de fútbol neerlandés",
  "Feyenoord":"Club de fútbol neerlandés",
  "Benfica":"Club de fútbol portugués",
  "Porto":"Club de fútbol portugués",
  "Sporting Lisboa":"Club de fútbol portugués",
  "Talleres":"Club de fútbol argentino",
"Talleres":"Club de fútbol argentino",
"Belgrano":"Club de fútbol argentino",
"Boca jr":"Club de fútbol argentino",
"River Plate":"Club de fútbol argentino",
"Newell's":"Club de fútbol argentino",
"Rosario Central":"Club de fútbol argentino",
"Racing":"Club de fútbol argentino",
"Independiente":"Club de fútbol argentino",
"Estudiantes de la Plata":"Club de fútbol argentino",
"Inter de Miami":"Club de fútbol estadounidense",
"El secreto de sus ojos":"Película argentina",
"Nueve reinas":"Película argentina",
"Relatos salvajes":"Película argentina",
"Esperando la carroza":"Película argentina",
"La historia oficial":"Película argentina",
"Argentina 1985":"Película argentina",
"El hijo de la novia":"Película argentina",
"La Odisea de los Giles":"Película argentina",
"Un novio para mi mujer":"Película argentina",
"Luna de Avellaneda":"Película argentina",
"Carancho":"Película argentina",
"Pizza birra faso":"Película argentina",
"El clan":"Película argentina",
"El aura":"Película argentina",
"Medianeras":"Película argentina",
"La odisea de los giles":"Película argentina",
"Mi obra maestra":"Película argentina",
"El robo del siglo":"Película argentina",
"Corazon de Leon":"Película argentina",
"Los simuladores":"Serie argentina",
"Casados con hijos":"Serie argentina",
"El marginal":"Serie argentina",
"Okupas":"Serie argentina",
"Tumberos":"Serie argentina",
"Vientos de agua":"Serie argentina",
"Hermanos y detectives":"Serie argentina",
"Graduados":"Serie argentina",
"El puntero":"Serie argentina",
"ATAV":"Serie argentina",
"Resistiré":"Serie argentina",
"Casi ángeles":"Serie argentina",
"Chiquititas":"Serie argentina",
"Floricienta":"Serie argentina",
"Las Estrellas":"Serie argentina",
"Showmatch":"Programa de TV",
"Videomatch":"Programa de TV",
"Polémica en el bar":"Programa de TV",
"Intratables":"Programa de TV",
"Periodismo para todos":"Programa de TV",
"PH Podemos Hablar":"Programa de TV",
"Almorzando con Mirtha Legrand":"Programa de TV",
"CQC":"Programa de TV",
"Bendita TV":"Programa de TV",
"LAM":"Programa de TV",
"MasterChef":"Programa de TV",
"Gran Hermano":"Reality show",
"Pasapalabra":"Programa de TV",
"El precio justo":"Programa de TV",
"Perros de la calle":"Programa radial",
"Basta de todo":"Programa radial",
"Peligro sin codificar":"Programa de TV",
"El Padrino":"Película famosa",
"El Padrino II":"Película famosa",
"Rocky":"Película famosa",
"Rambo":"Película famosa",
"Forrest Gump":"Película famosa",
"Titanic":"Película famosa",
"Avatar":"Película famosa",
"Inception":"Película famosa",
"Interestelar":"Película famosa",
"Gladiador":"Película famosa",
"Jurassic Park":"Película famosa",
"Volver al futuro":"Película famosa",
"Terminator":"Película famosa",
"Matrix":"Película famosa",
"Pulp Fiction":"Película famosa",
"El club de la pelea":"Película famosa",
"Batman":"Película de superhéroes",
"Avengers":"Película de superhéroes",
"Iron Man":"Película de superhéroes",
"Spider-Man":"Película de superhéroes",
"Star Wars":"Saga de ciencia ficción",
"Indiana Jones":"Saga de aventuras",
"Harry Potter":"Saga fantástica",
"El señor de los anillos":"Saga fantástica",
"Tiburon":"Película famosa",
"Rocky Balboa":"Película famosa",
"Top Gun":"Película famosa",
"Taxi Driver":"Película famosa",
"Scarface":"Película famosa",
"It":"Película de terror",
"Breaking Bad":"Serie famosa",
"Better Call Saul":"Serie famosa",
"Game of Thrones":"Serie famosa",
"The Walking Dead":"Serie famosa",
"Friends":"Serie de comedia",
"The Office":"Serie de comedia",
"Greys Anatomy":"Serie médica",
"Lost":"Serie famosa",
"Dr House":"Serie médica",
"Prison Break":"Serie famosa",
"Dexter":"Serie policial",
"Stranger Things":"Serie de ciencia ficción",
"Dark":"Serie de ciencia ficción",
"Peaky Blinders":"Serie histórica",
"Vikings":"Serie histórica",
"The Big Bang Theory":"Serie de comedia",
"Seinfeld":"Serie de comedia",
"Black Mirror":"Serie de ciencia ficción",
"The Boys":"Serie de superhéroes",
"La casa de Papel":"Serie española",
"Coscu":"Streamer argentino",
"Momo":"Streamer argentino",
"Spreen":"Streamer argentino",
"Tomas Rebord":"Creador de contenido",
"Ruffo (Blender)":"Creador de contenido",
"Ibai":"Streamer famoso",
"Luisito Comunica":"YouTuber famoso",
"Luquitas Rodríguez":"Streamer argentino",
"La Cobra":"Streamer argentino",
"Davoo Xeneize":"Streamer argentino",
"RodSquare":"Creador de contenido",
"Ricky Fort":"Figura mediática argentina",
"Martin Cirio":"Streamer argentino",
"Les Amateurs":"Canal de streaming",
"Olga":"Canal de streaming",
"Luzu TV":"Canal de streaming",
"Vorterix":"Canal de streaming",
"Blender":"Canal de streaming",
"Gelatina":"Canal de streaming",
"Paren la mano (Vorterix)":"Programa de streaming",
"Hay algo ahi (Blender)":"Programa de streaming",
"Nadie dice nada (Luzu)":"Programa de streaming",
"Soñé que volaba (Olga)":"Programa de streaming",
"Antes que nadie (Luzu)":"Programa de streaming",
"Oppenheimer":"Película famosa",
"Barbie":"Película famosa",
"The Crown":"Serie histórica",
"House of Cards":"Serie política",
"Narcos":"Serie policial",
"The Mandalorian":"Serie de ciencia ficción",
"The Simpsons":"Serie animada",
"South Park":"Serie animada",
"Rick and Morty":"Serie animada",
"Wednesday":"Serie famosa",
"Sergio Agüero":"Deportista argentino",
"Franco Colapinto":"Deportista argentino",
"Emanuel Ginóbili":"Deportista argentino",
"Luis Scola":"Deportista argentino",
"Juan Martín del Potro":"Deportista argentino",
"Guillermo Vilas":"Deportista argentino",
"Marcos Maidana":"Deportista argentino",
"Sergio Martínez":"Deportista argentino",
"Luciana Aymar":"Deportista argentina",
"Paula Pareto":"Deportista argentina",
"Martin Palermo":"Deportista argentino",
"Oscar Ruggeri":"Deportista argentino",
"Marcelo Tinelli":"Conductor de TV",
"Susana Giménez":"Conductora de TV",
"Mirtha Legrand":"Conductora de TV",
"Guillermo Francella":"Actor argentino",
"Ricardo Darín":"Actor argentino",
"Adrián Suar":"Actor argentino",
"Florencia Peña":"Actriz argentina",
"Luciano Castro":"Actor argentino",
"Marley":"Conductor de TV",
"Santiago del Moro":"Conductor de TV",
"Ángel de Brito":"Periodista argentino",
"Jorge Rial":"Periodista argentino",
"Viviana Canosa":"Periodista argentina",
"Pampita":"Modelo argentina",
"Yanina Latorre":"Figura mediática",
"Wanda Nara":"Figura mediática",
"Marcelo Polino":"Periodista argentino",
"Guido Kaczka":"Conductor de TV",
"Darío Barassi":"Conductor de TV",
"Charly García":"Músico argentino",
"Gustavo Cerati":"Músico argentino",
"Fito Páez":"Músico argentino",
"Spinetta":"Músico argentino",
"Indio Solari":"Músico argentino",
"Andrés Calamaro":"Músico argentino",
"Lali Espósito":"Cantante argentina",
"Tini Stoessel":"Cantante argentina",
"Nicki Nicole":"Cantante argentina",
"Duki":"Cantante argentino",
"Trueno":"Cantante argentino",
"Maria Becerra":"Cantante argentina",
"Bizarrap":"Productor musical",
"La Mona Jimenez":"Cantante argentino",
"Rodrigo Bueno":"Cantante argentino",
"Q Lokura":"Grupo musical",
"Joaco López":"Creador digital",
"Mernuel":"Creador digital",
"Ricardo Fort":"Figura mediática",
"Vicky Xipolitakis":"Figura mediática",
"Alex Caniggia":"Figura mediática",
"Charlotte Caniggia":"Figura mediática",
"Milei":"Político argentino",
"Peron":"Político argentino",
"Nestor Kirchner":"Político argentino",
"Cristina Kirchner":"Política argentina",
"Eva Peron":"Figura histórica argentina",
"Mauricio Macri":"Político argentino",
"Juan Domingo Perón":"Figura histórica argentina",
"Eva Perón":"Figura histórica argentina",
"Cristina Fernández":"Política argentina",
"Javier Milei":"Político argentino",
"Raúl Alfonsín":"Político argentino",
"Carlos Menem":"Político argentino",
"Domingo Sarmiento":"Figura histórica argentina",
"José de San Martín":"Prócer argentino",
"Manuel Belgrano":"Prócer argentino",
"Leonardo DiCaprio":"Actor de Hollywood",
"Brad Pitt":"Actor de Hollywood",
"Tom Cruise":"Actor de Hollywood",
"Johnny Depp":"Actor de Hollywood",
"Robert Downey Jr":"Actor de Hollywood",
"Al Pacino":"Actor de Hollywood",
"Robert De Niro":"Actor de Hollywood",
"Denzel Washington":"Actor de Hollywood",
"Will Smith":"Actor de Hollywood",
"Keanu Reeves":"Actor de Hollywood",
"Matt Damon":"Actor de Hollywood",
"Christian Bale":"Actor de Hollywood",
"Ryan Gosling":"Actor de Hollywood",
"Hugh Jackman":"Actor de Hollywood",
"Jason Statham":"Actor de Hollywood",
"Scarlett Johansson":"Actriz de Hollywood",
"Margot Robbie":"Actriz de Hollywood",
"Angelina Jolie":"Actriz de Hollywood",
"Jennifer Lawrence":"Actriz de Hollywood",
"Emma Stone":"Actriz de Hollywood",
"Michael Jackson":"Cantante internacional",
"Madonna":"Cantante internacional",
"Elvis Presley":"Cantante histórico",
"Queen":"Banda de rock",
"Freddie Mercury":"Cantante de rock",
"The Beatles":"Banda de rock",
"Paul McCartney":"Músico británico",
"John Lennon":"Músico británico",
"Beyoncé":"Cantante internacional",
"Rihanna":"Cantante internacional",
"Taylor Swift":"Cantante internacional",
"Lady Gaga":"Cantante internacional",
"Bruno Mars":"Cantante internacional",
"Drake":"Cantante internacional",
"Eminem":"Rapero famoso",
"Kanye West":"Rapero famoso",
"Justin Bieber":"Cantante internacional",
"Shakira":"Cantante latina",
"Bad Bunny":"Cantante latino",
"The Weeknd":"Cantante internacional",
"Daddy Yankee":"Cantante latino",
"Michael Jordan":"Deportista internacional",
"LeBron James":"Deportista internacional",
"Kobe Bryant":"Deportista internacional",
"Stephen Curry":"Deportista internacional",
"Roger Federer":"Tenista famoso",
"Rafael Nadal":"Tenista famoso",
"Novak Djokovic":"Tenista famoso",
"Usain Bolt":"Atleta olímpico",
"Mike Tyson":"Boxeador famoso",
"Elon Musk":"Empresario tecnológico",
"Bill Gates":"Empresario tecnológico",
"Steve Jobs":"Empresario tecnológico",
"Mark Zuckerberg":"Empresario tecnológico",
"Jeff Bezos":"Empresario tecnológico",
"Barack Obama":"Político internacional",
"Donald Trump":"Político internacional",
"Einstein":"Científico famoso",
"Stephen Hawking":"Científico famoso",
"Bruce Lee":"Actor de acción",
"Oprah Winfrey":"Conductora famosa",
"Kim Kardashian":"Figura mediática",
"Selena Gomez":"Cantante famosa",
"Jackie Chan":"Actor de acción",
"Tom Hanks":"Actor famoso",
"Morgan Freeman":"Actor famoso",
"Jack Nicholson":"Actor famoso",
"Silla":"Mueble del hogar",
"Mesa":"Mueble del hogar",
"Sillón":"Mueble del hogar",
"Cama":"Mueble del hogar",
"Almohada":"Objeto del dormitorio",
"Colchón":"Objeto del dormitorio",
"Lámpara":"Objeto del hogar",
"Ventilador":"Electrodoméstico",
"Aire acondicionado":"Electrodoméstico",
"Televisor":"Electrodoméstico",
"Control remoto":"Objeto electrónico",
"Cortina":"Objeto del hogar",
"Espejo":"Objeto del hogar",
"Reloj de pared":"Objeto del hogar",
"Cuadro":"Decoración del hogar",
"Plato":"Utensilio de cocina",
"Vaso":"Utensilio de cocina",
"Taza":"Utensilio de cocina",
"Cuchara":"Utensilio de cocina",
"Tenedor":"Utensilio de cocina",
"Cuchillo":"Utensilio de cocina",
"Sartén":"Utensilio de cocina",
"Olla":"Utensilio de cocina",
"Horno":"Electrodoméstico",
"Microondas":"Electrodoméstico",
"Heladera":"Electrodoméstico",
"Licuadora":"Electrodoméstico",
"Pava eléctrica":"Electrodoméstico",
"Cafetera":"Electrodoméstico",
"Tostadora":"Electrodoméstico",
"Celular":"Objeto tecnológico",
"Computadora":"Objeto tecnológico",
"Notebook":"Objeto tecnológico",
"Tablet":"Objeto tecnológico",
"Mouse":"Accesorio informático",
"Teclado":"Accesorio informático",
"Monitor":"Objeto tecnológico",
"Impresora":"Objeto tecnológico",
"Router":"Dispositivo de red",
"Modem":"Dispositivo de red",
"Auriculares":"Accesorio electrónico",
"Parlante":"Accesorio electrónico",
"Cargador":"Accesorio electrónico",
"Batería":"Accesorio electrónico",
"Disco rígido":"Dispositivo informático",
};